# Generated by Django 3.1.1 on 2020-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('quota', models.IntegerField(default=10)),
                ('used', models.IntegerField(default=0)),
                ('last_used_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
