# Generated by Django 3.1.1 on 2020-12-28 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytcore', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_used_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
