# Generated by Django 3.1.4 on 2020-12-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytcore', '0003_auto_20201228_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=200),
        ),
    ]
